"""empty message

Revision ID: 36978210761d
Revises: a8df8473b09c
Create Date: 2026-05-12 01:09:13.198923

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36978210761d"
down_revision: Union[str, Sequence[str], None] = "a8df8473b09c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=20), server_default="user", nullable=False),
    )
    op.drop_column("users", "is_superuser")
    op.create_check_constraint(
        "check_role", "users", "role IN ('superuser', 'admin', 'user')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_superuser",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
