"""empty message

Revision ID: a8df8473b09c
Revises: 3f784160f211
Create Date: 2026-05-08 21:50:57.140968

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8df8473b09c"
down_revision: Union[str, Sequence[str], None] = "3f784160f211"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("doctors", sa.Column("photo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doctors", "photo")
    # ### end Alembic commands ###
