"""empty message

Revision ID: b93a57bf3c08
Revises: b4b6f37aa05b
Create Date: 2026-05-19 23:10:46.154877

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b93a57bf3c08"
down_revision: Union[str, Sequence[str], None] = "b4b6f37aa05b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "education",
        "title",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=712),
        existing_nullable=False,
    )
    op.alter_column(
        "extra_education",
        "title",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=712),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "extra_education",
        "title",
        existing_type=sa.String(length=712),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "education",
        "title",
        existing_type=sa.String(length=712),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
