"""empty message

Revision ID: c99dab55aa3b
Revises: 3b833db6a976
Create Date: 2026-02-12 22:03:01.758612

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c99dab55aa3b"
down_revision: Union[str, Sequence[str], None] = "3b833db6a976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("equipment_types", "photo_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment_types",
        sa.Column("photo_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
